title:              Zhuang Kang
email:              z.kang1009@gmail.com
description:     
author:             Zhuang Kang
baseurl:            "/zk.git.io"
url:                "https://github.com/Proskahn"
# Social Profiles
# twitter_username:   
github_username:    Proskahn
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
